package foo

import foo "github.com/curtisallen/mockery-bug/foo"
import mock "github.com/stretchr/testify/mock"

// MockFoo is an autogenerated mock type for the Foo type
type MockFoo struct {
	mock.Mock
}

// Something provides a mock function with given fields:
func (_m *MockFoo) Something() foo.Data {
	ret := _m.Called()

	var r0 foo.Data
	if rf, ok := ret.Get(0).(func() foo.Data); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(foo.Data)
	}

	return r0
}
